# build environment
FROM node:13.12.0-alpine as build

# set work dir
WORKDIR /app

# add node modules to PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent

# copy files and run app
COPY . ./
RUN npm run build
CMD [ "npm", "start"]